# Generated by Django 2.2.9 on 2023-03-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230316_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id',
            new_name='order_id',
        ),
    ]
