# Generated by Django 4.1.7 on 2023-03-15 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_auto_20230316_0032"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(
                choices=[
                    ("Gold", "Gold"),
                    ("Grossary", "Grossary"),
                    ("Investment", "Investment"),
                    ("mutual fund", "mutual fund"),
                ],
                default="Gold",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recieved_user",
            field=models.ForeignKey(
                default=22,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reciever",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="stripe_id",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
